### ISSUE TITLE
mysql de phpbb en modo lectura

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#11]
Tenemos que definitivamente dejar la base de datos de phpbb bloqueada para que no se pueda escribir, ya que tenemos el foro viejo como archivo y no lo vamos a actualizar nunca más.

**Comment by nukeador** [comment]
@stripTM ¿crees que cambiando permisos al usuario de mysql simplemente valdrá? ¿O dará problemas de carga el cms?

Quizá tendríamos también que separar las tablas a otra bdd a modo de "archivo"

**Comment by pochy-ja** [comment]
@nukeador mi experiencia con otros CMS es que si necesita escribir alguna veces para registros de acceso que se hacen en BD algunas veces, hace mucho que no veo dentro de PHPBB pero valdría la pena mirar el esquema de la base de datos haber que información se guarda en las tablas para que te des cuenta si poniendo el usuario con acceso de lectura puede funcionar, lo que estas queriendo es que ningun usuario modifique/añada información? o que consuma recursos/espacio en el servidor?

**Comment by nukeador** [comment]
No necesitamos que la gente pueda iniciar sesión. El objetivo es:
- Que el contenido sea accesible para la gente que llegue desde los buscadores.
- Que no tengamos que mantener el cms ya que no se va a actualizar nunca más.

**Comment by pochy-ja** [comment]
No me refería a que iniciaran sesión los usuarios, igual en algunas acciones los CMSs hacen registros de las visitas, pero en fin, creo que solo quedaría probarlo? para saber si levanta el foro y salir de duda.

**Comment by nukeador** [comment]
Sería interesante si podemos presentar todo el contenido de phpbb como archivo, pero sin tener instalado phpbb. Aunque bloqueemos la bdd, es una aplicación que no mantenemos y un problema de seguridad.

**Comment by nukeador** [comment]
phpbb ya no carga con el servidor y hemos decidido redireccionar a SUMO https://foro.mozilla-hispano.org/t/jubilacion-de-los-foros-viejos/23482/
