### ISSUE TITLE
Adecentar mediawiki

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#13]
- [x] Levantar mediawiki en el servidor restaurado
- [ ] Actualizar plugins
- [x] Actualizar/activar skin MH
- [x] Activar SemanticMediaWiki

**Comment by nukeador** [comment]
Podemos aprovechar para hacer #2 a la vez

**Comment by willyaranda** [comment]
Yo esta noche me encargo de levantar tanto box como foro antiguo y documentación. Una vez esté, podemos hacer #2

**Comment by willyaranda** [comment]
Actualizado a la última (1.25), pero se ve como el culo. La skin que tenemos, no existe.

**Comment by stripTM** [comment]
Repasar como se hacen los skins y hacer uno nuevo o ver si el antiguo es reaprovechable https://www.mediawiki.org/wiki/Manual:Skin_configuration

**Comment by nukeador** [comment]
He actualizado la descripción general con una lista de tareas a realizar para poder dar este issue como cerrado.

**Comment by nukeador** [comment]
SemanticMW está activo pero parece que no detecta el contenido que teníamos previamente. Hay que ver si ha cambiado la sintaxis o qué.

**Comment by nukeador** [comment]
El idioma del wiki estaba mal, ahora parece que aparecen cosas en SMW. Falta mirar las extensiones para mapas y calendario.

**Comment by nukeador** [comment]
SMW ya funciona, instalé extensiones adicionales para calendario y mapas.

**Comment by nukeador** [comment]
@stripTM ¿Puedes crear un issue en el repo de la web para hacer un skin basado en el default que al menos tenga la cabecera y pie? Luego vamos iterando, pero al menos tener algo super rápido funcional.

**Comment by nukeador** [comment]
@stripTM ¿Puedes crear un issue en el repo de la web para hacer un skin basado en el default que al menos tenga la cabecera y pie? Luego vamos iterando, pero al menos tener algo super rápido funcional.

**Comment by nukeador** [comment]
Veo que el plugin que proporciona cmobox no está activado. Lo necesitamos para la página de /Colabora

**Comment by stripTM** [comment]
Creado, esta semana me centro en esto.
https://github.com/mozillahispano/mozilla-hispano.org/issues/285

**Comment by nukeador** [comment]
He copiado y activado la extensión cmo para que funcionen los bloques en 

https://www.mozilla-hispano.org/documentacion/Colabora

He tenido que editarla porque referenciaba rutas del skin antiguo, y he tenido que copiar una carpeta /icons dentro del skin nuevo.

**Comment by nukeador** [comment]
@stripTM ¿en qué quedó esta tarea?

**Comment by stripTM** [comment]
Cogimos como base el skin Foreground y se hicieron los ajustes necesarios para que 'respire' Mozilla Hispano https://github.com/mozillahispano/mozilla-hispano.org/commit/8f8c6be57d45578c40c3ce106a4dae6711c1336a

Con el tiempo que ha pasado no tiene pinta que se vayan a hacer más cambios con lo que por mi podemos dar por finalizada la tarea.
