### ISSUE TITLE
Migrar enlaces a imágenes en artículos de wp de http a https

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/administracion-tecnica#19]

**Comment by stripTM** [comment]
Esos enlaces están en el propio texto del artículo, con lo que la migración tiene que ir dirigida a cambiar los propios artículos

**Comment by nukeador** [comment]
Hay un plugin que hace exactamente esto, no recuerdo el nombre

**Comment by stripTM** [comment]
Lo he instalado, lo que hace es sustituir las rutas al vuelo cuando se genera la página, como lo de migrar los artículos no parece complicado voy a ir a por esa opción, así tenemos un plugin menos.
