### ISSUE TITLE
Actualización MediaWiki

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#2]
Necesitamos actualizar mediawiki y sus plugins.

En especial teniendo cuidado con no romper plugins esenciales como el de SemanticMediaWiki.

**Comment by pochy-ja** [comment]
El plugin esta abandonado?, lo podrían actualizar igual? o les a dado problemas anteriormente?

**Comment by nukeador** [comment]
No, no lo está, pero puede que haya cambiado temas de sintaxis o cómo usarlo que pueda involucrar más acciones.

**Comment by nukeador** [comment]
@willyaranda esto ya está ¿no?
