### ISSUE TITLE
Levantar box

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/administracion-tecnica#20]
Levantar http://box.mozilla-hispano.org/

**Comment by nukeador** [comment]
Levantado y actualizado.

Pendiente:

Ver que el login con persona funciona.
Aumentar el tamaño de subida (ahora 2MB), dado que no usamos apache:

https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html#using-php-fpm

**Comment by willyaranda** [comment]
Hecho
