### ISSUE TITLE
Levantar stats piwik

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/administracion-tecnica#22]

**Comment by stripTM** [comment]
Error 500 en los php, porque intenta hacer requires de cosas que no encuentra

**Comment by nukeador** [comment]
Voy a dar un vistazo

**Comment by nukeador** [comment]
Hay que revisar, primero bajar la ultima version de piwik y luego ver si hay alguna peculiaridad para ejecutar con php-fpm

**Comment by stripTM** [comment]
Levantada
