### ISSUE TITLE
Filtros nauscópicos para ABP dan 404

### ISSUE THREAD

**Issue by ThePhoenixBird** [mozillahispano/administracion-tecnica#23]
Los filtros alojados en http://abp.mozilla-hispano.org/nauscopio/filtros.txt dan error 404

**Comment by willyaranda** [comment]
me lo asigno, y los activo durante esta mañana

**Comment by willyaranda** [comment]
Levantado

**Comment by willyaranda** [comment]
http://abp.mozilla-hispano.org/nauscopio/filtros.txt
