### ISSUE TITLE
Levantar antiguo foro phpbb

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#27]
Dado que el foro phpbb tiene miles de respuestas de asistencia indexadas por los motores de búsqueda y era la primera fuente de tráfico, deberíamos levantarlo lo antes posible.

**Comment by nukeador** [comment]
@willyaranda ¿te lo asignaste para hacer? ¿tienes alguna fecha estimada? No se si @stripTM estaba mirándolo también.

**Comment by willyaranda** [comment]
Si lo mira stripTM, genial, porque yo estoy muy liado

**Comment by nukeador** [comment]
@stripTM ¿Qué errores da ahora o qué fue lo último que probaste?

**Comment by nukeador** [comment]
He copiado los archivos que habia en stage porque parece que estaban dañados en prod e instalado php-apc. Parece que está levantado:

https://www.mozilla-hispano.org/foro/
