### ISSUE TITLE
La barra de administración de WP no se ve correctamente

### ISSUE THREAD

**Issue by Josexv1** [mozillahispano/administracion-tecnica#29]
Hola, esto no se si es un error, pero no recuerdo haberlo notado antes hay un espacio anormal en la parte superior del frente de Mozilla hispano como pueden ver esta imagen 
![xdd](https://cloud.githubusercontent.com/assets/12077848/9650422/6228f584-51cc-11e5-9983-c26935728eef.png) en https://www.mozilla-hispano.org/

**Comment by fjaguero** [comment]
¿Te refieres al borde blanco? Eso es porque Wordpress está metiendo la barra de administración. Sólo lo ves si estás logueado, no lo ven los demás usuarios.

**Comment by Josexv1** [comment]
Claro, así es, pero no debería ver el toolbar de wordpress en lugar de la el espacio?

**Comment by fjaguero** [comment]
En efecto. Tampoco creo que sea muy prioritario, pero se puede dejar como issue para que sea arreglado.

**Comment by fjaguero** [comment]
Ups, acabo de ver que el issue está en la repo de administración técnica, pero debería estarlo en el de [mozilla-hispano.org](https://github.com/mozillahispano/mozilla-hispano.org). ¿Podrías crearlo ahí?
