### ISSUE TITLE
Actualización a Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#3]
Sería bueno pasar el server a ubuntu 14.04 LTS.

Habría que hacer una lista de cosas que se pueden romper, como por ejemplo los .htaccess de algún CMS que contengan directivas que en el nuevo apache no estén permitidas.

**Comment by stripTM** [comment]
¿Si montamos una máquina virtual con 14.04 y montamos un script que nos 'rsycronice' los archivos y bases de datos.

Aunque me temo que son muchos gigas.

**Comment by nukeador** [comment]
Son muchísimos. Tenemos backup de todo si algo se rompiera.

**Comment by stripTM** [comment]
Entoces la estrategia sería montar una virtual con el ubuntu que tenemos ahora, hacer el montaje de ngix, apache, mysql, wordpress, discourse que hay ahora, actualizar y ver que problemas van surgiendo.

**Comment by nukeador** [comment]
¿Alguien tiene tiempo para esto? Creo que va a ser mucho trabajo duplicar todo lo que tenemos, porque una cosa son las configuraciones y otra los datos.

**Comment by stripTM** [comment]
En julio empezaré a tener más tiempo, pero el problema lo tengo con la configuración inicial, de los montajes distintos de LAMP (ej. ngix, python...) lo tengo muy verde.

**Comment by pochy-ja** [comment]
Hace un tiempo le envié un correo a @nukeador con una propuesta de colaboración que se estaba necesitando en esta área y entendí perfectamente su respuesta, se que es un poco compleja como para iniciarse sin tener acceso a la infraestructura de todo lo que teneís montado  y es un riesgo, pero bueno si necesitais alguna ayuda desde fuera para el tema de la migración con algunos problemas o consejos comentaré con gusto en cada issues que se genere, llevo mucho tiempo leyendo las listas(deprecated) y el foro, estoy al tanto bastante de todo lo que se a comentado. Saludos y al tanto.

**Comment by nukeador** [comment]
Gracias @pochy-ja

Creo que nos sería útil tener claro qué cambios de Ubuntu 12.04 a 14.04 pueden generar conflictos: Nginx, apache, php, mysql principalmente, ya que supongo que hay cosas que han cambiado y hay que tener cuidado.

Si tienes tiempo para investigar sobre ello creo que nos sería de mucha ayuda para esta actualización :D

**Comment by pochy-ja** [comment]
@nukeador bueno te comento que uso en mi lap personal algo basado en 14.04 así que estoy más que familiarizado, teneis pensado hacer un upgrade al sistema o instalación limpia?

Sobre la investigación en cuestión les comento:

Versiones de los software a día de hoy por sistema en sus repositorios respectivos

12.04: Nginx - 1.1.19, Apache - 2.2.22, PHP - 5.3.10 y Mysql - 5.5.43
14.04: Nginx - 1.4.6, Apache - 2.4.7, PHP - 5.5.9 y Mysql - 5.5.43

Comenzando desde el final, mi opnión es!

1) Mysql va de lujo, teneis la misma versión por lo que no debe haber problema de ningun tipo, de hecho la semana pasada hice una migración de mysql a mariadb y todo fue sin contratiempos.

2) PHP creo que a no ser que tengan algun sotfware que este programado de hace mucho tiempo y utilize funciones deprecated, no debe haber contratiempos tampoco, nos los tuve en mi momento, para mi PHP 5.4 fue una versión de transición, pase muy rápido de 5.3 a 5.5, en desarrollo y en producción.

3) Apache fue el único que puso resistencia pues cambiaron un poco algunas directivas de configuración y seguridad, pero es cosa de una tarde cogerle la vuelta, realmente no sé que módulos usan ustedes pero no me vi muy afectado en cuanto a los que uso que van en funcion de autenticación, subversion, proxy inverso, redirecciones, ssl, directorios de usuarios y sin contar los que traer por defecto activado que vienen previamente preparados para el cambio de versión o sea con soporte a viejas directivas y demás, lo virtualhost si tienen que escribirlos como van o no levantan, pero no es nada del otro mundo que (apachectl -t) no te avise. :-)

4) Nginx: Aquí no creo que existan problemas tampoco, salvo alguna directiva específica que se puede identificar igualmente, aunque siempre me mantengo con el estable del ppa e hice upgrade de versiones sin problemas cuando comenzaron a salirle vulnarabilidades a la que estaba en los repositorios, conlos archivos de configuración de los sistema que tenía publicados en su momento no tuve contratiempos, tambien uso nginx de proxy inverso y va de lujo hasta el momento, lo que me preocupa que si aun estan usando la versión que viene en los repositorios, les recomiendo que se actualizan alguna superior pues así por arribita me encontré con estos bugs que debe tener esa versión:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701112
http://mailman.nginx.org/pipermail/nginx-announce/2013/000114.html
http://mailman.nginx.org/pipermail/nginx-announce/2013/000125.html
http://mailman.nginx.org/pipermail/nginx-announce/2014/000135.html

Lo recomendable es actualizarse del ppa pues el mantenedor del paquete a veces es un poco lento :-) , y en las nuevas vienen características muy interesantes, En este momento desconosco si han parcheado la versión vieja que venía en el repositorio.

https://launchpad.net/~nginx/+archive/ubuntu/stable

Disculpen que me haya extendido tanto en el comentario.

Saludos

**Comment by nukeador** [comment]
Con la muerte del servidor, esto ha quedado actualizado, veremos con qué problemas nos encontramos al levantar todo. Crearemos tareas individuales para cada cosa.
