### ISSUE TITLE
stats.mozilla-hispano.org caído

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#30]
https://stats.mozilla-hispano.org/

403 Forbidden

**Comment by nukeador** [comment]
@stripTM esto estaba funcionando antes no? No se el tiempo que lleva caído y estamos perdiendo stats de todo el tiempo que siga así :S

**Comment by stripTM** [comment]
Si, se quedo funcionando, hace unos días lo consulté para ver que volviamos a tener las visitas habituales

**Comment by stripTM** [comment]
Está funcionado https://stats.mozilla-hispano.org/index.php lo que quedaría es ver si nos interesa hacer la redirección del / a /index.php
