### ISSUE TITLE
Reportes pesados de piwik tiran php5-fpm

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#34]
Si se ejecutan reportes pesados en piwik el proceso php5-fpm deja de responder y aunque no consume muchos recursos no sirve las páginas con PHP.

Habría que solucionar esto, aislando cada web php en un proceso y aumentando los recursos que puede consumir para poder ejecutar estos reportes.

**Comment by pochy-ja** [comment]
Si, me a pasado, la idea es aislarlos en pools, me han comentado de una herramienta muy genial[1] y [2] que automatiza toda esta tarea, fue un colega que trabaja en un centro de datos, les vendría bien una automatización para todas las web que tienen de las comunidades locales y proyectos, además que contribuye a la seguridad del ambiente de ejecución!

Pero si quieren ensuciarse las manos y hacerlo a lo directo, pueden guiarse por estos [3]  y [4] enlaces que fue con los que cogí el getting started del tema!

[1] https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx
[2] http://www.ansible.com/how-ansible-works
[3] http://blog.desdelinux.net/hostear-vhosts-con-usuarios-diferentes-nginx/
[4] http://blog.ngen.com.ar/configuracion-segura-de-un-webserver-con-nginx-php-fpm/

**Comment by nukeador** [comment]
No parece que haya vuelto a pasar.
