### ISSUE TITLE
Nuevo proyecto de Control de calidad no aparece en el sitio

### ISSUE THREAD

**Issue by gaby2300** [mozillahispano/administracion-tecnica#42]
He creado un nuevo proyecto como perteneciente al área de Control de calidad (Exprimiendo Firefox OS) pero no consigo que aparezca en la página del área. Probé Actualizar, Trasladar y limpiar cache pero nada resultó...

Nuke me sugirió abrir un issue aquí, por eso lo hago.

Muchas gracias!
Saludos,
Gabriela

**Comment by gaby2300** [comment]
Podrá alguien revisar esto por favor?

Muchas gracias!!!

**Comment by stripTM** [comment]
Me puedes dar un poco de más información, me lo comentó @nukeador el fin de semana pero no he estado en casa y no le pedí más detalles.

¿En que página debería aparecer?

**Comment by gaby2300** [comment]
Hola @stripTM !

Fui a la página para pasarte el enlace y me di cuenta que ya apareció como uno de los proyectos así que... Se nota que ya se resolvió aunque vaya a saber cómo... 

Como sea, muchas gracias!!!

**Comment by stripTM** [comment]
Genial :-)

**Comment by gaby2300** [comment]
Así es!!! Gracias!!
