### ISSUE TITLE
Revisión general del planet

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#6]
Revisión de estabilidad del planet.

**Comment by nukeador** [comment]
@stripTM ¿En qué estado quedó este tema?

**Comment by stripTM** [comment]
Con los arreglos y limpieza de fuentes rss problemáticas quedó estable, pero merece ser revisado ya que por ejemplo la parte de twitter o flickr cambiaron el api y está ahora en blanco.

**Comment by nukeador** [comment]
La pregunta es, ¿merece mantener moonmoon o mover el planet a WP?

**Comment by stripTM** [comment]
Pues seguro que ahora ya tenemos para wordpress plugins que nos hacen esta tarea.

**Comment by nukeador** [comment]
OK, entonces cierro aquí y dejo en el backlog la intención de migrarlo dentro de WP en #10
