### ISSUE TITLE
Entradas importadas en WP locas

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/administracion-tecnica#8]
WP, supongo que por el plugin de rss cientos de veces repetidas.

Hay que ver qué pasa y limpiar:

http://www.mozilla-hispano.org/wp-admin/edit.php?post_status=pending&amp;post_type=post

**Comment by nukeador** [comment]
@FrancJP ¿Crees que lo mejor es borrar todo? En el último año no veo que haya habido importaciones muy locas, parece que es de hace años todo.

**Comment by francjp** [comment]
Ok por mí, yo era más que nada para hacer limpieza y no tener esa cantidad de entradas atrasadas sin publicar muertas de risa.

**Comment by nukeador** [comment]
Uf, hay como 580 páginas de entradas a borrar. Cambiando las opciones son 12 páginas de 999 entradas, pero el servidor no deja procesarlo por "414 Request-URI Too Large"

@willyaranda ¿Alguna idea para procesar este borrado de forma sencilla?

**Comment by willyaranda** [comment]
podemos tirar de phpMyAdmin para borrarlos, acabaríamos antes

**Comment by nukeador** [comment]
Buff, pero ¿y todas las conexiones entre tablas que pueda haber? Es muy arriesgado eso.

/cc @stripTM

**Comment by pochy-ja** [comment]
Y si usan un plugin para ello?
https://wordpress.org/plugins/bulk-delete/
Permite filtros, condiciones y demás, quisas lo puedan dejar automatizado por si siguen apareciendo entradas "locas"  :-)

**Comment by stripTM** [comment]
Buen apunte el de @pochy-ja

**Comment by nukeador** [comment]
@stripTM @willyaranda si tenéis un rato para probar esto adelante. Si no, yo podría mirarlo en unos días.

**Comment by nukeador** [comment]
Esto quedó finalizado por webdev y noticias ¿no?

Ping @francjp @fjaguero

**Comment by nukeador** [comment]
Al parecer esto lo solucionaron desde webdev y noticias. Cerramos.

**Comment by francjp** [comment]
Confirmo que ya está solucionado... y creo que no se rompió nada afortunadamente ;)
